# Generated by Django 5.2.10 on 2026-01-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_maintenance_task_report_pdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenancetask",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
