# Generated by Django 5.2.10 on 2026-01-06 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenancetask",
            name="report_pdf",
            field=models.FileField(blank=True, null=True, upload_to="reports/"),
        ),
    ]
